### ISSUE TITLE
add support for target containing slash

### ISSUE THREAD

**Issue by dfeyer** [shini4i/pre-commit-makefile#12]
We use a lots of target like "make setup/ci" or even with multiple slashed segment. Can be nice if those target are visible in the readme. Thanks

**Comment by shini4i** [comment]
Hi @dfeyer!

Thanks for pointing this out! Somehow, I didn't realize that it's a valid target name. You can try version `v0.2.2`, it should work now.

**Comment by shini4i** [comment]
Closed by #13
